### PR TITLE
Support whitespaces in filename 

### PR DESCRIPTION
**Pull request by MrEcl**
Little fix to add support for whitespaces and line brakes in filename.

### CODE REVIEW

**Review by dougwilson — CHANGES_REQUESTED** [review]
Thanks! If you can, please add a test and also link to either the specification that says this is allowed in the file name or the docs for whatever client is sending these chara.

**Comment by MrEcl** [comment]
Thanks for a fast response! 

Docs for whitespaces support:

- Windows [https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/file-folder-name-whitespace-characters](url)
- macOS [https://ss64.com/osx/syntax-filenames.html](url)

Unfortunately I am not so much familiar with tests. Do you have any suggestion how can i provide it?

**Comment by dougwilson** [comment]
Yes,whitespace can be in filenames, butfor multipart forms they are supposed yo be encoded per the spec. I don't see anywherethay they are allowed to be sent unencoded. This module decodes them. They should be coming in as `%20`.

**Comment by MrEcl** [comment]
Well... they are not :)  Try to upload file with name that includes 0x2028 (\u2028). Stream will be closed. 
This char is common when copy/pasting text from Figma.

**Comment by dougwilson** [comment]
What client is performing the upload? I am happy to add this is you can link to where in the multipart/formdata specification it says this is allowed. It could very well be the client is buggy. But you didnt provide links to where in the multipart/formdata specification it says this is allowed or to the client's documentation that says it will do this. I am happy to reopen if you can provide this information.

Or even a packet capture of the multupart upload occurring that has this character in it would be helpful and I can try and get the above from that.

**Pull request closed without merging**
