### PR TITLE
Add support for headers with unquoted name and filename

### PR DESCRIPTION
**Pull request by juankaram**
Hello Andrew!

I made some changes to the project to support a small edge case that is triggered when the client send the multipart headers without quotes for the name and the file name, i hope you like it and its up to the project standards. Please feel no pressure to accept it or not, is totally up to you! 

Thank you for maintaining the project and taking your time to review this!

### CODE REVIEW

**Comment by andrewrk** [comment]
Code looks fine and it comes with a test, which is nice.

I vaguely recall something about this not being spec compliant or something but I can't really remember. To be honest I never read the HTTP multipart spec.

So what I'm going to do is wait for @dougwilson to chime in just in case, and if he has nothing to say for a week, then I'll go ahead and merge this.

**Comment by dougwilson** [comment]
Hey! Yes, the idea is sound: that filenames do not have to be quoted, but only if they consist entirely of token characters. I think the PR should be updated to be more restrictive in that way.

In addition, your regular expressions don't seem quite right. For example, your regular expression `/\bname="?([^"]+)("|; )/i` does not match as you may expect:
```
// old way
/\bname="?([^"]+)("|; )/i.exec("name=\"foo\"")
["name="foo"", "foo", """]

// only the trailing quote; incorrect as the trailing quote it part of the name
/\bname="?([^"]+)("|; )/i.exec("name=foo\"")
["name=foo\"", "foo", """]

// no quotes at all; match fails
/\bname="?([^"]+)("|; )/i.exec("name=foo")
null
```

Your updated filename regular expression fails in similar ways:
```
// quoted; matches fine
/\bfilename=(.*?)($|; )/i.exec("filename=\"foo\"")
["filename=\"foo\"", "\"foo\"", ""]

// your match eats into other parameters incorrectly
/\bfilename=(.*?)($|; )/i.exec("filename=foo;fizz=buzz")
["filename=foo;fizz=buzz", "foo;fizz=buzz", ""]
```

**Comment by dougwilson** [comment]
Hi @CurveBeryl, do you still have any interest in making the above adjustments?

**Comment by dougwilson** [comment]
I cannot accept this PR. Please see the above comments as to why.

**Pull request closed without merging**
